//go-ebuild insipred by cargo-ebuild
// rappidly proto-magicked into exitstance with CHATGPT
// chatGPT got mad PhD level up... helping killer skills...  :-)
// copywrite bla...
// cant embed directly ? "github.com/williamh/get-ego-vendor"
// would make for muliplatfor/ssh work easier and portable...

package writeEbuild

// BASE go icudes cleaner this way
import (
	"base.go"
)
//BASE go icudes


func writeEbuild(path, version string, licenses []struct { Type string }) {
    // Generate the metadata for the ebuild.
    pkg := strings.ReplaceAll(path, "/", "-")
           metadata := fmt.Sprintf(`# Generated by go-ebuild
                                   EAPI=7
                                        inherit go-module
                                        GITHUB_USER=user
                                                GITHUB_REPO=%s
                                                        EGO_SUM="%s"
                                                                LICENSE="%s"
                                                                        `, path, version, licenses[0].Type)

                       // Prompt the user for the file path to save the ebuild.
                       var filepath string
                       fmt.Print("Enter file path to save ebuild: ")
                       if _, err := fmt.Scanln(&filepath);
    err != nil {
        log.Fatal(err)
    }

    // Write the metadata and build instructions to the ebuild file.
    f, err := os.Create(filepath)
    if err != nil {
    log.Fatal(err)
    }
    defer f.Close()
    f.WriteString(metadata)
    f.WriteString(fmt.Sprintf(`src_compile() {
        go-module_src_compile
    }

    src_install() {
        go-module_src_install
    }
    `))
    fmt.Printf("Ebuild file saved to %s\n", filepath)
}