/*
Copyright © 2023 NAME HERE <EMAIL ADDRESS>

*/
package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

// writeEbuild.goCmd represents the writeEbuild.go command
var writeEbuild.goCmd = &cobra.Command{
	Use:   "writeEbuild.go",
	Short: "writ the ebuild out to a file...",
	Long: `A longer description that spans multiple lines and likely contains examples
and usage of using your command. For example:

Cobra is a CLI library for Go that empowers applications.
This application is a tool to generate the needed files
to quickly create a Cobra application.`,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("writeEbuild.go called")
	},
}

func init() {
	rootCmd.AddCommand(writeEbuild.goCmd)
func writeEbuild(path, version string, licenses []struct { Type string }) {
    // Generate the metadata for the ebuild.
    pkg := strings.ReplaceAll(path, "/", "-")
           metadata := fmt.Sprintf(`# Generated by go-ebuild
                                   EAPI=7
                                        inherit go-module
                                        GITHUB_USER=user
                                                GITHUB_REPO=%s
                                                        EGO_SUM="%s"
                                                                LICENSE="%s"
                                                                        `, path, version, licenses[0].Type)

                       // Prompt the user for the file path to save the ebuild.
                       var filepath string
                       fmt.Print("Enter file path to save ebuild: ")
                       if _, err := fmt.Scanln(&filepath);
    err != nil {
        log.Fatal(err)
    }

    // Write the metadata and build instructions to the ebuild file.
    f, err := os.Create(filepath)
    if err != nil {
    log.Fatal(err)
    }
    defer f.Close()
    f.WriteString(metadata)
    f.WriteString(fmt.Sprintf(`src_compile() {
        go-module_src_compile
    }

    src_install() {
        go-module_src_install
    }
    `))
    fmt.Printf("Ebuild file saved to %s\n", filepath)
}
}
